---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by v2.
--- DateTime: 2023/05/19 19:22
---

---Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
--
--1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
--By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

local maxn = 4*(10^6)
local fibonacci = {1,2}
local i = 1
local sum = 0
while fibonacci[i] < maxn do
    if fibonacci[i] % 2 == 0 then
        sum = sum + fibonacci[i]
    end
    fibonacci[i+2]=fibonacci[i+1] + fibonacci[i]
    i = i+1
end

print(fibonacci[10])
print(sum)