---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by v2.
--- DateTime: 2023/05/24 20:49
---A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
---Find the largest palindrome made from the product of two 3-digit numbers.


local palindromes = {}

function reverseString(str)
    local reversed = ""
    for i = str:len(), 1, -1 do
        reversed = reversed .. str:sub(i, i)
    end
    return reversed
end

for l=100,1000-1 do
    for m=100,1000-1 do
        local num = l*m
        local str_num = tostring(num)
        if string.sub(str_num,1,3) == reverseString(string.sub(str_num,-3,-1)) then
            palindromes[#palindromes+1] = num
        end
    end
end

table.sort(palindromes)
print("Answer :", palindromes[#palindromes])