---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by v2.
--- DateTime: 2023/05/20 15:42
---
local number  = 600851475143
local prime_factors = {}

for i=1,math.sqrt(number) do
    if number % i ==0 then
        for j=2,i,1 do
            if i % j == 0 then
                prime_factors[#prime_factors+1] = j
                break
            end
        end
    end
end

table.sort(prime_factors)
print("Answer :", prime_factors[#prime_factors])