---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by v2.
--- DateTime: 2023/05/19 14:33
---

---question
--If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
--Find the sum of all the multiples of 3 or 5 below 1000.

---define the maximum number(ex:10)
maximum_number = 1000

---define tables that hold the multiples
multiples_3 = {}
multiples_5 = {}
multiples_15 = {}

---append multiples to tables
function append_multiples()
    i = 1
    while i < maximum_number do

        if i % 3 == 0 then
            multiples_3[#multiples_3+1] = i
        end
        if i % 5 == 0 then
            multiples_5[#multiples_5+1] = i
        end
        if i % 15 == 0 then
            multiples_15[#multiples_15+1] = i
        end

    i = i+1

    end
    return multiples_3, multiples_5, multiples_15
end

---debug and run
append_multiples()


---add numbers in multiples_3 and multiples_5 while removing numbers in multiples_15

length_3x = #multiples_3
length_5x = #multiples_5
length_15x = #multiples_15

total_sum = 3*length_3x*(length_3x+1)/2 + 5*length_5x*(length_5x+1)/2 - 15*length_15x*(length_15x+1)/2

print("answer",total_sum)


