# -*- coding: utf-8 -*-
"""
Created on Sun May  8 20:34:54 2022

@author: ggZubrowka
"""

"""Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 find the sum of the even-valued terms."""
 
l = []

def f(x):
     
     if x ==1 or x==2:
         return x
         

     else:
         A = f(x-1) + f(x-2)
         return A
      

x = 1    

while f(x) <4000000:
    
    if f(x)%2 == 0:
           
       l.append(f(x))
    
    x = x+1
    
print(sum(l))
    
    
 
 